apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reloader-reloader
  name: reloader-reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-reloader
  template:
    metadata:
      labels:
        app: reloader-reloader
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          value: REPLACE_WITH_TARGET_NAMESPACE
        image: REPLACE_WITH_RELOADER_IMAGE_PATH
        imagePullPolicy: IfNotPresent
        name: reloader-reloader
        args:
      serviceAccountName: ua-cloud-monitoring                                        