#--------------------------------------------------------------------------
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corporation 2019.
#
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corporation.
#--------------------------------------------------------------------------

kind: Pod
apiVersion: v1
metadata:
  namespace: ibm-common-services
  name: dummy-db
  labels:
    app: dummy-db
spec:
  containers:
    - image: quay.io/bitnami/nginx:latest
      securityContext:
        runAsUser: 0
        seLinuxOptions:
             type: spc_t
      name: nginx
      volumeMounts:
        - name: mongodump
          mountPath: "/dump"
      lifecycle:
            postStart:
              exec:
                command: ["bash", "-c", "rm -rf /dump/.velero"]
  volumes:
    - name: mongodump
      persistentVolumeClaim:
        claimName: my-mongodump
