kind: Pod
apiVersion: v1
metadata:
  namespace: ibm-common-services
  name: dummy-db
  labels:
    app: dummy-db
spec:
  containers:
    - image: quay.io/bitnami/nginx:latest
      name: nginx
      volumeMounts:
        - name: mongodump
          mountPath: "/dump"
      lifecycle:
            postStart:
              exec:
                command: ["bash", "-c", "rm -rf /dump/.velero"]
  volumes:
    - name: mongodump
      persistentVolumeClaim:
        claimName: my-mongodump
