apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: uapluginrepos.monitoring.management.ibm.com
  labels:
    app.kubernetes.io/name: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/instance: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/managed-by: ibm-monitoring-dataprovider-mgmt-operator
spec:
  group: monitoring.management.ibm.com
  names:
    kind: UAPluginRepo
    listKind: UAPluginRepoList
    plural: uapluginrepos
    singular: uapluginrepo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      description: "Deploy Unified Agent plugins repo. For additional details regarding
        installation parameters, see [IBM Monitoring DataProvider Management documentation](https://ibm.biz/monitoring_dataprovider).
        By installing this product, accept the license terms at http://ibm.biz/cp4mcm-23-license."
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: UAPluginRepoSpec defines the desired state of MonitoringDeploy
          properties:
            imagePullSecret:
              type: string
          required:
          - imagePullSecret
          type: object
        status:
          description: UAPluginRepoStatus defines the observed state of MonitoringDeploy
          properties:
            conditions:
              description: Conditions contains the list of the conditions fulfilled
              items:
                properties:
                  message:
                    description: Message
                    type: string
                  reason:
                    description: Reason
                    type: string
                  status:
                    description: Status of the condition, one of (\"True\", \"False\", \"Unknown\")
                    type: string
                  type:
                    description: type of condition
                    type: string
                required:
                - type
                - status
                - reason
                - message
                type: object
              type: array
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
