apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: remoteagentdeploys.monitoring.management.ibm.com
  labels:
    app.kubernetes.io/name: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/instance: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/managed-by: ibm-monitoring-dataprovider-mgmt-operator
spec:
  group: monitoring.management.ibm.com
  names:
    kind: RemoteAgentDeploy
    listKind: RemoteAgentDeployList
    plural: remoteagentdeploys
    singular: remoteagentdeploy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      description: "RemoteAgentDeploy is the Schema for the RemoteAgentDeploy.monitoring.management.ibm.com
        API \n Documentation \n For additional details regarding install parameters
        check: http://ibm.biz/cp_kcwelcomefam. \n License \n By installing this product
        you accept the license terms http://ibm.biz/cp4mcm-22-license."
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RemoteAgentDeploySpec defines the desired state of MonitoringDeploy
          properties:
            targetNamespace:
              type: string
            uaPluginRepo:
              type: string
          required:
          - targetNamespace
          - uaPluginRepo
          type: object
        status:
          description: RemoteAgentDeployStatus defines the observed state of MonitoringDeploy
          properties:
            conditions:
              description: Conditions contains the list of the conditions fulfilled
              items:
                properties:
                  message:
                    description: Message
                    type: string
                  reason:
                    description: Reason
                    type: string
                  status:
                    description: Status of the condition, one of (\"True\", \"False\", \"Unknown\")
                    type: string
                  type:
                    description: type of condition
                    type: string
                required:
                - type
                - status
                - reason
                - message
                type: object
              type: array
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
