# Source: ibm-ua-operator/templates/ua.ibm.com_v1alpha1_ua_cr.yaml
apiVersion: ua.ibm.com/v1alpha1
kind: UA
metadata:
  name: ua-mgmt
spec:
  ibmAgentConfigSecret: "dc-secret"
  ibmAgentHTTPSSecret: "ibm-agent-https-secret"
  image: REPLACE_WITH_IMAGE_FULL_PATH
  interval: 1m
  resources:
    memory: 512Mi
    cpu: 500m
