apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-monitoring-dataprovider-mgmt-operator
  labels:
    app.kubernetes.io/name: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/instance: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/managed-by: ibm-monitoring-dataprovider-mgmt-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-dataprovider-mgmt-operator
  template:
    metadata:
      labels:
        name: ibm-monitoring-dataprovider-mgmt-operator
        app.kubernetes.io/name: ibm-monitoring-dataprovider-mgmt-operator
        app.kubernetes.io/instance: ibm-monitoring-dataprovider-mgmt-operator
        app.kubernetes.io/managed-by: ibm-monitoring-dataprovider-mgmt-operator
      annotations:
        cloudpakId: "7f6eda41081c4e08a255be1f0b4aef2d"
        cloudpakName: "IBM Cloud Pak for Multicloud Management"
        cloudpakVersion: "2.3.25"
        productID: "b6fe4d9823294584822155cd2595445b"
        productName: "CP4MCM Advanced Monitoring"
        productVersion: "2.3.25"
        productMetric: "MANAGED_VIRTUAL_SERVER"
        productChargedContainers: "All"
        productCloudpakRatio: "1:1"
        olm.relatedImage.autconfigoperator: cp.icr.io/cp/cp4mcm/ibm-dc-autoconfig-operator@sha256:b3ecb5920daaa08009111c3ba303dae1a8f0919de7a2b6919e09b9a3a01e7a55
        olm.relatedImage.k8monitor: cp.icr.io/cp/cp4mcm/k8-monitor@sha256:bde6cb952fded7a143de56b3931651a171cd95d85096dd9bd12656e2234aa442
        olm.relatedImage.k8operator: cp.icr.io/cp/cp4mcm/k8sdc-operator@sha256:f04707be1fd0155405660948a19a5f7dd752ad8e645d91c433f17be9d0763d72
        olm.relatedImage.reloader: cp.icr.io/cp/cp4mcm/reloader@sha256:3d3942ed5bd4813598eb1940aa2f2cc23e99768394c7da2c7efd6ec196f0b704
        olm.relatedImage.uacloud: cp.icr.io/cp/cp4mcm/ua-cloud-monitoring@sha256:71e8ddc8ed82d09e78c2d9b475572194a0ae032904c759b9ef553a0b2940e733
        olm.relatedImage.uaoperator: cp.icr.io/cp/cp4mcm/ua-operator@sha256:12ad6a21e2018fbb1ad0f9a5acb1735a48a6ab9c25e29142a9a764cc2afe3449
        olm.relatedImage.uaplugins: cp.icr.io/cp/cp4mcm/ua-plugins@sha256:7a741e979be05a146a6eb50601859a6f87f9e768a16e9f691ca19f6990b57fae
        olm.relatedImage.uarepo: cp.icr.io/cp/cp4mcm/ua-repo@sha256:102f916534fd7d915e2ee0e25cd59bb9413a2aa5887e1b1ce8df04728070f827
    spec:
      serviceAccountName: ibm-monitoring-dataprovider-mgmt-operator
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: operator
          # Replace this with the built image name
          image: cp.icr.io/cp/cp4mcm/ibm-monitoring-dataprovider-mgmt-operator@sha256:3a603cda2c6af31655b0bdf9062d3c99e32653b474ad9b20cdf4264fd92ae64f
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-dataprovider-mgmt-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: AUTO_CONFIG
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.autconfigoperator']
            - name: K8MONITOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.k8monitor']
            - name: K8SDC_OPERATOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.k8operator']
            - name: RELOADER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.reloader']
            - name: UACLOUD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uacloud']
            - name: UAOPERATOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uaoperator']
            - name: UAREPO
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uarepo']
            - name: UAPLUGINS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uaplugins']
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1500m
              memory: 768Mi
            requests:
              cpu: 800m
              memory: 512Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: runner
          emptyDir: {}
