apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-monitoring-dataprovider-mgmt-operator
  labels:
    app.kubernetes.io/name: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/instance: ibm-monitoring-dataprovider-mgmt-operator
    app.kubernetes.io/managed-by: ibm-monitoring-dataprovider-mgmt-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-dataprovider-mgmt-operator
  template:
    metadata:
      labels:
        name: ibm-monitoring-dataprovider-mgmt-operator
        app.kubernetes.io/name: ibm-monitoring-dataprovider-mgmt-operator
        app.kubernetes.io/instance: ibm-monitoring-dataprovider-mgmt-operator
        app.kubernetes.io/managed-by: ibm-monitoring-dataprovider-mgmt-operator
      annotations:
        cloudpakId: "7f6eda41081c4e08a255be1f0b4aef2d"
        cloudpakName: "IBM Cloud Pak for Multicloud Management"
        cloudpakVersion: "2.3.25"
        productID: "b6fe4d9823294584822155cd2595445b"
        productName: "CP4MCM Advanced Monitoring"
        productVersion: "2.3.25"
        productMetric: "MANAGED_VIRTUAL_SERVER"
        productChargedContainers: "All"
        productCloudpakRatio: "1:1"
        olm.relatedImage.autconfigoperator: cp.icr.io/cp/cp4mcm/ibm-dc-autoconfig-operator@sha256:c769dc0908d9cc413fe8360705a783b9f21e2bfe706719f25afcfe73a1124c21
        olm.relatedImage.k8monitor: cp.icr.io/cp/cp4mcm/k8-monitor@sha256:39b992b48e1273496fad5944f14a16b7a8a126c43cd2bbacdb1f7fe4f8eb7b66
        olm.relatedImage.k8operator: cp.icr.io/cp/cp4mcm/k8sdc-operator@sha256:819ad4e01d91229b36cbbbb45790a1adefaa0f812ba4a22992226d58a5454f7a
        olm.relatedImage.reloader: cp.icr.io/cp/cp4mcm/reloader@sha256:2ddce2d315dfcb9dbd4a7a4c2eb3df0fa842ee17ca5dacafe848265a3ebefa16
        olm.relatedImage.uacloud: cp.icr.io/cp/cp4mcm/ua-cloud-monitoring@sha256:48a771a9787b8071c3dc80e60260d95d6afe8c3314cfa7dc4c1a9453b2c86f07
        olm.relatedImage.uaoperator: cp.icr.io/cp/cp4mcm/ua-operator@sha256:7bf8c312f8915880cc691b71ee8bccb5bad26e8b75986094558563e895218626
        olm.relatedImage.uaplugins: cp.icr.io/cp/cp4mcm/ua-plugins@sha256:90f68c20beac3836ea3df3536d09be43feea019469054ff75b902da5d108448a
        olm.relatedImage.uarepo: cp.icr.io/cp/cp4mcm/ua-repo@sha256:b9c5bac67bb2c7775c3e4503185fcd4d138fde71af74913875249698d661d763
    spec:
      serviceAccountName: ibm-monitoring-dataprovider-mgmt-operator
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: operator
          # Replace this with the built image name
          image: cp.icr.io/cp/cp4mcm/ibm-monitoring-dataprovider-mgmt-operator@sha256:c5e4a2cc6b8f040a167a5a8062674600858a82b9730996d6769d513a69765c80
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-dataprovider-mgmt-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: AUTO_CONFIG
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.autconfigoperator']
            - name: K8MONITOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.k8monitor']
            - name: K8SDC_OPERATOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.k8operator']
            - name: RELOADER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.reloader']
            - name: UACLOUD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uacloud']
            - name: UAOPERATOR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uaoperator']
            - name: UAREPO
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uarepo']
            - name: UAPLUGINS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.relatedImage.uaplugins']
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1500m
              memory: 768Mi
            requests:
              cpu: 800m
              memory: 512Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: runner
          emptyDir: {}
